# Generated by Django 3.2.13 on 2022-10-21 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='reivew',
            new_name='review',
        ),
    ]
